=== koda7v/minispec/Resource/MinispecAttribute2.dtd
<?xml version="1.0" encoding="UTF-8"?>

<!ELEMENT Model (entity*)>
	<!ATTLIST Model name CDATA "">

<!ELEMENT entity (attribute*)>
	<!ATTLIST entity name CDATA "">
	
<!ELEMENT attribute (objet*)>
	<!ATTLIST attribute name CDATA "">
	<!ATTLIST attribute type CDATA "">
	
<!ELEMENT objet (#PCDATA)>
	<!ATTLIST objet name CDATA "">

=== koda7v/minispec/Resource/minispec2.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE Model PUBLIC "MinispecId" "MiniSpecAttribute2.dtd">
<Model name="satbat">
	<entity name="Satellite">
		<attribute name="nomSat" type="String"/>
		<attribute name="id" type="Integer"/>
		<attribute name="parent" type="Flotte"/>
		<attribute name="panneauSolaires" type="List" min="0" max="10">
			<objet name="PanneauSolaire"/>
		</attribute>
	</entity>
	<entity name="PanneauSolaire">
		<attribute name="nomPan" type="String"/>
		<attribute name="id" type="Integer"/>
		<attribute name="parent" type="Satellite"/>
	</entity>
	<entity name="Flotte">
		<attribute name="nomFlo" type="String"/>
		<attribute name="id" type="Integer"/>
		<attribute name="satellites" type="List">
			<objet name="Satellite"/>
		</attribute>
	</entity>
</Model>
